### DISCUSSION TITLE
Running Semaphore in Docker successfully (and with BoltDB)

### DISCUSSION THREAD

**Discussion by bverkron** [semaphoreui/semaphore#1040] [General]
I found that the example in the documentation for semaphore doesn't work as-is. The only way I could get it working was using an from here and doing some tweaking: https://computingforgeeks.com/run-semaphore-ansible-in-docker/

Additionally I originally wanted to use BoltDB as my requirements are very light (home lab basically) and I don't have the need or desire to run a full MySQL DB on my low resource mini server.

This is what I have so far but would love to switch to BoltDB. Happy to submit a PR for the Docker related documentation if / when we get it working. Note that I usually chose to use bind mounts instead of volumes to make manipulating and backing up the configuration files, etc easier. I've also changed some ports to avoid conflicts with other things I have running on this docker host.

```yaml
version: '2'
services:

  mysql-semaphore:
    image: mysql:5.6
    ports:
      - 3303:3306
    container_name: mysql-semaphore
    hostname: mysql-semaphore
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: semaphore_db
      MYSQL_USER: semaphore_user
      MYSQL_PASSWORD: ********
    volumes:
      - /home/master/semaphore/mount_mysql:/var/lib/mysql

  semaphore:
    ports:
      - 3003:3000
    image: semaphoreui/semaphore:latest
    container_name: semaphore
    environment:
      SEMAPHORE_DB_USER: semaphore_user
      SEMAPHORE_DB_PASS: ********
      SEMAPHORE_DB_HOST: mysql-semaphore
      SEMAPHORE_DB_PORT: 3306
      SEMAPHORE_DB: semaphore_db
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: ********
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: ********@gmail.com
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: ********
    volumes:
      - /home/master/semaphore/mount_semaphore:/home/semaphore
      - /home/master/semaphore/mount_etc_semaphore:/etc/semaphore
    depends_on:
      - mysql-semaphore
```

Some of my attempts at getting BoltDB working are listed in this issue: https://github.com/ansible-semaphore/semaphore/issues/1037

**Comment by bverkron** [comment]
I made this fresh start and while I didn't get any errors the container just stops after attempting to connect for about 30 seconds or so.

```yaml
version: '2'
services:
  semaphore:
    ports:
      - 3003:3000
    image: semaphoreui/semaphore:latest
    container_name: semaphore-bolt
    environment:
      # SEMAPHORE_DB_USER: semaphore_user
      # SEMAPHORE_DB_PASS: passwortd
      # SEMAPHORE_DB_HOST: mysql-semaphore
      # SEMAPHORE_DB_PORT: 3306
      # SEMAPHORE_DB: semaphore_db
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: password
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: admin@admin.com
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: INkXeElIFBJUfy3xF0b59T/qMJgsvldmnGi3tKQ71KU=
    volumes:
      - /home/master/semaphore_bolt/mount_semaphore:/home/semaphore
#      - /home/master/semaphore_bolt/mount_etc_semaphore:/etc/semaphore
```

container log output
```
Attempting to connect to database semaphore on 0.0.0.0:3306 with user semaphore ...
.............................
```

I also tried with no volume section at all (so it would presumably create a docker volume instead of a bind mount) and same result. 

I also tried bind mounting the /etc/semaphore path (uncommented `- /home/master/semaphore_bolt/mount_etc_semaphore:/etc/semaphore`) and putting the following config in it (and none at all) but got exactly the same result.

```json
{

        "bolt": {
                "host": "/home/semaphore/database.boltdb",
                "user": "",
                "pass": "",
                "name": "",
                "options": null
        },
        "dialect": "bolt",
        "port": "",
        "interface": "",
        "tmp_path": "/tmp/semaphore",
        "cookie_hash": "****",
        "cookie_encryption": "****",
        "access_key_encryption": "*****",
        "email_sender": "",
        "email_host": "",
        "email_port": "",
        "email_username": "",
        "email_password": "",
        "web_host": "",
        "ldap_binddn": "",
        "ldap_bindpassword": "",
        "ldap_server": "",
        "ldap_searchdn": "",
        "ldap_searchfilter": "",
        "ldap_mappings": {
                "dn": "",
                "mail": "",
                "uid": "",
                "cn": ""
        },
        "telegram_chat": "",
        "telegram_token": "",
        "slack_url": "",
        "max_parallel_tasks": 0,
        "email_alert": false,
        "email_secure": false,
        "telegram_alert": false,
        "slack_alert": false,
        "ldap_enable": false,
        "ldap_needtls": false,
        "ssh_config_path": "",
        "demo_mode": false
 }
```

It seems like it completely ignores that it's a bolt db and tries to connect on a address and 3306 port as if it's expecting a mysql db. Bolt shouldn't be using a port, should it?
