### DISCUSSION TITLE
Help with Snapcraft Semaphore

### DISCUSSION THREAD

**Discussion by ySp-chld** [semaphoreui/semaphore#1096] [Q&A]
Hello,
I am using an ansible playbooks that needs to write files in /etc/ansible so it can do stuff.
However running Semaphore using snapcraft as recommanded I can only see that this is not working.
What could be my option on such issue (rewriting this huge playbook provided by an editor is not really my safest option) ? 
Is there a writable path inside the snapcraft ? 
Could I add connections at runtime I don't give a thing about running snapcraft in restricted mode if I can run it with access to local /etc/ansible in read write that would probably be the easiest for me.
Any advice on such situation, maybe I can relocate ANSIBLE_CONFIG to a writable path inside the snapcraft ?
Thank you for any input on that and sorry if it's the wrong place to ask.

Have a nice day.

**Comment by ySp-chld** [comment]
OK A bit more context :
This si what causing the issue : 
```
- name: Security Plugin configuration | Download certificates generation tool
  local_action:
    module: get_url
    url: https://search.maven.org/remotecontent?filepath=com/floragunn/search-guard-tlstool/1.5/search-guard-tlstool-1.5.tar.gz
    dest: /tmp/opensearch-nodecerts/search-guard-tlstool.tar.gz
  run_once: true
  when: configuration.changed
  become: false
```

In that case the action tries to download a file locally and execute it which is not unreasonable but I guess is not authorized by snap restricted mode ( I really would love to understand what was behind this idea of using snap in restricted mode and recommend this method over the rest).  
Any way i there an easy way to move out of that paradigm without rewriting all the playbooks ? 
If I decide to reinstall outside snapcraft is there a way to transfer my database to local installation ?
