### DISCUSSION TITLE
Adding lib hcloud does not help to run playbook: Failed to import the required Python library

### DISCUSSION THREAD

**Discussion by ahoiroman** [semaphoreui/semaphore#1405] [Q&A]
Hi there,

I am using semaphore in a docker env and created a little custom docker file:

```
FROM semaphoreui/semaphore:latest

USER root
RUN apk add --no-cache python3 py3-pip
USER semaphore
RUN pip install hcloud
```

After editing the `docker-compose.yml` like this

```
services:
  mysql:
    restart: unless-stopped
    image: mysql:8.0
    hostname: mysql
    volumes:
      - semaphore-mysql:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
  semaphore:
    build: .
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      SEMAPHORE_DB_USER: ${DB_USER}
      SEMAPHORE_DB_PASS: ${DB_PASSWORD}
      SEMAPHORE_DB_HOST: mysql # for postgres, change to: postgres
      SEMAPHORE_DB_PORT: 3306 # change to 5432 for postgres
      SEMAPHORE_DB_DIALECT: mysql
      SEMAPHORE_DB: ${DB_NAME}
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      SEMAPHORE_ADMIN_NAME: ${ADMIN_USER}
      SEMAPHORE_ADMIN_EMAIL: ${ADMIN_PASSWORD}
      SEMAPHORE_ADMIN: ${ADMIN_MAIL}
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: ${ENCRYPTION_KEY}
    depends_on:
      - mysql # for postgres, change to: postgres
volumes:
  semaphore-mysql: # to use postgres, switch to: semaphore-postgres
```

I was able to access semaphore.

A short check to ensure hcloud is installed:

```
docker exec -it 6af1f8353fad pip list
Package            Version
------------------ ---------
aiohttp            3.8.1
aiosignal          1.2.0
ansible            5.8.0
ansible-core       2.13.6
appdirs            1.4.4
async-timeout      4.0.2
attrs              21.4.0
bcrypt             3.2.2
certifi            2023.7.22
cffi               1.15.0
charset-normalizer 3.2.0
contextlib2        21.6.0
cryptography       3.4.8
frozenlist         1.2.0
hcloud             1.27.1
idna               3.4
idna-ssl           1.1.0
Jinja2             3.0.3
MarkupSafe         2.1.1
more-itertools     8.13.0
multidict          6.0.2
ordered-set        4.0.2
packaging          21.3
paramiko           2.11.0
pep517             0.12.0
pip                22.1.1
pyasn1             0.4.8
pycparser          2.20
PyNaCl             1.5.0
pyparsing          2.4.7
python-dateutil    2.8.2
PyYAML             6.0
requests           2.31.0
resolvelib         0.5.4
retrying           1.3.3
setuptools         59.4.0
six                1.16.0
tomli              2.0.1
typing_extensions  4.2.0
urllib3            2.0.4
yarl               1.7.2
```

Looks nice. 

But now if I want to run my playbook:

```
TASK [Create a basic server] ***************************************************
11:28:41 PM
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (hcloud-python) on 6af1f8353fad's Python /usr/bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}
```

And this is what I don't understand. Why is it telling me that it cannot import the lib? It should be there...
