### DISCUSSION TITLE
Proposed Workflow Enhancement Request

### DISCUSSION THREAD

**Discussion by TKILLAHOME** [semaphoreui/semaphore#1495] [Ideas]
It would be great if there were a "Workflow" section after "Dashboard" where various templates could be clicked together in a specific order to execute different playbooks/roles in a certain sequence. I think this is a missing feature. Personally, I would find such a feature useful. What do you think, [fiftin](https://github.com/ansible-semaphore/semaphore/commits?author=fiftin)?

**Comment by rbohyra** [comment]
Bump for this feature, this feature is really needed to be added to semaphore

**Comment by fiftin** [comment]
How this should works? Each run of first task in the sequence should trigger the sequence? Or sequence must be triggered explicitly?

**Comment by rbohyra** [comment]
I was thinking about workflow as a ability to define a sequence of tasks that need to be executed in order. I suggest adding it as an additional tab on the left side (under Task Template/Schedule). A few points below: 
1. Vars are actually specified in each prepared tasks, so workflow will just start already configured task, but survey variables should also be as additional option in workflow template. And I am wondering if adding environment variables to the workflow on the same way we have args in template its ok or not.  
2. Semaphore must support for conditional execution of tasks based on success or failure of previous tasks.
3. Possibility to add workflow to schedule jobs. 
I guess this will enhance Semaphore’s capabilities by providing a way to automate and streamline multi-step processes :)

**Reply by jengstrom440** [reply]
I am assuming you are asking for something similar like in Ansible Automation Platform 2 or AWX, where you can string together multiple playbooks based on success or failure? If it helps. you can make a mail.yaml file, and from there call playbooks in order. You should be able to register success or failure and take action based on those. I use something like this, to keep my code small and purpose built, so I can reuse them over:



```
  - name: Server Bootstrap
    hosts: all
    gather_facts: true
    tasks:
      - name: Print Connection Data
        include_tasks: 9_connection.yaml
  
      - name: Run test for winping
        include_tasks: 10_winping.yaml
  
      - name: Set Time Zone to Central
        include_tasks: 12_win_timezone.yaml
  
      - name: Add AD RSAT PowerShell
        include_tasks: 14_add_rsat_powershell.yaml
```

This way they execute in order. Not as pretty as a workflow, but is gets some of the things done. The numbers are just so you can visualize them easier in VSCode so you know which one executes in order on the file tree like a task sequence. Hope that helps.
