### DISCUSSION TITLE
Check / Update role dependancy that is in GIT

### DISCUSSION THREAD

**Discussion by webtroter** [semaphoreui/semaphore#1530] [Q&A] [answered]
Hello,

I have this `roles/requirements.yml`.

```yaml
- name: role-example
  scm: git
  src: ssh://git@git.example.org/Roles/role-example
  version: main
```

My problem is that the role isn't updated to the latest commit because the requirements.yml doesn't change.

Is there a way to trigger an update of my roles?

Or is my method not ok? I have one repo with all my playbooks, and many roles repos.

Thank you all
