### DISCUSSION TITLE
sudo user can't execute commands - getting 'This command has to be run under the root user.' error msg

### DISCUSSION THREAD

**Discussion by danieleperera** [semaphoreui/semaphore#1573] [Q&A]
Hi everyone,

I wanted to share some progress I’ve made with Semaphore setup. 
I'm using FreeIPA an open source identity management system, I've created a user who is allowed to launch commands with privileged permissions. However, when I try to use the same user with Semahore, I'm getting this error message: 
`This command has to be run under the root user.`

Below the yaml file of the task template:
```
- name: Update yum packages
  hosts: all
  become: true
  tasks:
    - name: Update packages with yum
      yum:
        name: '*'
        state: latest
```

With the same user, I'm able to log into the host and launch yum updates.
Below the yaml file that I'm using to debug:
```
- name: Update dnf packages
  hosts: all
  gather_facts: yes
  tasks:
    - name: Get current user on remote
      ansible.builtin.shell: |
        whoami
      become: yes
      become_method: sudo
      become_user: root
      register: out
    - debug:
        msg: "{{ out }}"
```
I'm running semaphore v2.9.37 via docker compose.
Any support would be greatly appreciated.
