### DISCUSSION TITLE
github action that invokes semaphore api and poll for a result

### DISCUSSION THREAD

**Discussion by gulbinas** [semaphoreui/semaphore#1617] [Show and tell]
Hello, I have made a working prototype and wanted to share here, maybe it would be some interest.

https://github.com/gulbinas/semaphore-action

Basic setup:

- have installed ansible semaphore on server(not publicly accessible)
- on same server installed docker
- also installed and configured github runner instance(github runner initialises connection from host to github, so no ports are open on server, thats nice)

found and forked [libpython-semaphore-client](https://github.com/gulbinas/libpython-semaphore-client), but it didn't worked with websocket endpoint to poll status of task, so for that I have used websockets python library

Here is an example of `.github/workflows/deploy.yml`:

```
name: deploy

on:
  push:
    branches: [ beta, ui ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: do deployment using ansible semaphore API call
      uses: gulbinas/semaphore-action@main
      id: deploy_step
      with:
        myInput: 29
        api_key: "api key"
        api_url: ""
        ws_api_url: ""
        project_id: ""
```

Please, bear in mind thats a first prototype to prove a concept, so everything is a total mess:)
As far as I looked there is no straightforward way to use ansible semaphore from github actions, so please let me know if there is any use for somebody.

Also, PR's and ideas are welcome:)

j.
