### DISCUSSION TITLE
Key Store Error ("Request failed with status code 400") Types of keys that fail are Login/Password and SSH. NONE keys do work

### DISCUSSION THREAD

**Discussion by alvaro-rrdt** [semaphoreui/semaphore#1702] [Q&A]
As the title says I am trying to set up either a SSH key or login/password but it doesnt work for login/password or SSH keys for NONE it does work no problem but I need to use either SSH or login/password the thing is trying to do that I get all the time the following error "Request failed with status code 400"

**Comment by Runningman-work** [comment]
Same issue here when adding a key to the key store -> request failed with status code 400.
I have installed semaphore via docker compose, The app and db are running and I can access the  web interface:

```
services:
  db:
    container_name: semaphore-db
    restart: unless-stopped
    env_file: stack.env
    image: postgres:16
    hostname: postgres
    volumes: 
      - /storage/semaphore/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  app:
    container_name: semaphore-app
    restart: unless-stopped
    env_file: stack.env
    ports:
      - 3000:3000
    image: semaphoreui/semaphore:latest

    environment:
      - SEMAPHORE_DB_USER=${POSTGRES_USER}
      - SEMAPHORE_DB_PASS=${POSTGRES_PASSWORD}
      - SEMAPHORE_DB_HOST=postgres
      - SEMAPHORE_DB_PORT=5432
      - SEMAPHORE_DB_DIALECT=postgres
      - SEMAPHORE_DB=${POSTGRES_DB}
      - SEMAPHORE_PLAYBOOK_PATH=${SEMAPHORE_PLAYBOOK_PATH}
      - SEMAPHORE_ADMIN_PASSWORD=${SEMAPHORE_ADMIN_PASSWORD}
      - SEMAPHORE_ADMIN_NAME=${SEMAPHORE_ADMIN_NAME}
      - SEMAPHORE_ADMIN_EMAIL=${SEMAPHORE_ADMIN_EMAIL}
      - SEMAPHORE_ADMIN=${SEMAPHORE_ADMIN}
      - SEMAPHORE_ACCESS_KEY_ENCRYPTION=${SEMAPHORE_ACCESS_KEY_ENCRYPTION}
      - TZ=Europe/Berlin
    depends_on:
      - db
```

I only have a mapped "postgres" directory in the filesystem, not one for "semaphore". Is that the issue?

regards,
Stefan

**Comment by CFenner** [comment]
Did one of you solve this?

**Reply by Runningman-work** [reply]
I can't remember how I fixed this, but as you can see I have also mapped a volume into filsystem for semaphore now (and also some minor modifications network-wise for my reverse proxy):

```
services:
  db:
    container_name: semaphore-db
    restart: unless-stopped
    env_file: stack.env
    image: postgres:16
    volumes: 
      - /path/to/semaphore/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - semaphore-net
  app:
    container_name: semaphore-app
    restart: unless-stopped
    env_file: stack.env
    ports:
      - 3000:3000
    image: semaphoreui/semaphore:latest
    environment:
      - SEMAPHORE_DB_USER=${POSTGRES_USER}
      - SEMAPHORE_DB_PASS=${POSTGRES_PASSWORD}
      - SEMAPHORE_DB_HOST=db
      - SEMAPHORE_DB_PORT=5432
      - SEMAPHORE_DB_DIALECT=postgres
      - SEMAPHORE_DB=${POSTGRES_DB}
      - SEMAPHORE_PLAYBOOK_PATH=${SEMAPHORE_PLAYBOOK_PATH}
      - SEMAPHORE_ADMIN_PASSWORD=${SEMAPHORE_ADMIN_PASSWORD}
      - SEMAPHORE_ADMIN_NAME=${SEMAPHORE_ADMIN_NAME}
      - SEMAPHORE_ADMIN_EMAIL=${SEMAPHORE_ADMIN_EMAIL}
      - SEMAPHORE_ADMIN=${SEMAPHORE_ADMIN}
      - SEMAPHORE_ACCESS_KEY_ENCRYPTION=${SEMAPHORE_ACCESS_KEY_ENCRYPTION}
      - TZ=Europe/Berlin
    volumes:
      - /path/to/semaphore/data:/var/lib/semaphore
    depends_on:
      - db
    networks:
      - semaphore-net
      - proxy-net
networks:
  semaphore-net:
    driver: bridge
  proxy-net:
    external: true
```

Hope it helps.

Stefan
