### DISCUSSION TITLE
[Docker/K8s] Openid/OIDC configuration

### DISCUSSION THREAD

**Discussion by abeastmal** [semaphoreui/semaphore#1914] [Q&A] [answered]
I noted is not possible to pass an ENV var to the container to configure OpenId/OIDC

Is there a workaround in place for docker/k8s users?

Thanks!

**Comment by abeastmal** [comment, marked as answer]
Found a workaround myself, by creating a configmap with the full config and mounting it in the container :shrug:

**Reply by fiftin** [reply]
Could you provide more details for other users?

**Reply by abeastmal** [reply]
I'm not sure if this is the best approach, but

* I deployed normally with a kubernetes deployment (passing the ENV vars, database, users, passwords, etc)
* Copied the resulting file from the container (at /etc/semaphore/config.json)
* Created a configmap with the resulting file (incluiding passwords, users, etc)
* Created an init container like
```
        - name: init
          image: busybox
          command: ["sh", "-c", "cp /etc/config/config.json /etc/semaphore"]
          volumeMounts:
            - name: semaphore-config
              mountPath: /etc/config
            - name: semaphore-volume
              mountPath: /etc/semaphore
```
* And finally added a command like this to avoid the container starting semaphore itself, starting it "manually", specifying my config.json file

```command: ["sh", "-c", "sleep 10 && semaphore server --config /etc/semaphore/config.json"] ```

The Github button appears but it seems that with the latest image, OIDC does not work
I see the message ``` level=error msg="claim 'email' missing or has bad format" ```

It only works, partially, with version v2.9.56. The github login works but the user & email that appear in the UI is a string of random chars. And there is no way to assign privileges, it seems?
