### DISCUSSION TITLE
No Websocket answers with traefik

### DISCUSSION THREAD

**Discussion by rebortg** [semaphoreui/semaphore#1920] [Q&A]
Hi,

I am trying to configure semapahore with Traefik reverse proxy in Docker.
I can't get the websockets to work.

I have other services with working websockets with a similar setup.

```
semaphore:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.semaphore.rule=Host(`semaphore.local.local`)"
      - "traefik.http.routers.semaphore.entrypoints=websecure"
      - "traefik.http.routers.semaphore.tls.certresolver=myresolver"
      - "traefik.http.services.semaphore.loadbalancer.server.port=3000"
```

```
traefik:
    image: "traefik:v2.11"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--accesslog=true"
      - "--accesslog.filepath=/logs/access.log"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.caserver=http://acme.local.local"
      - "--certificatesresolvers.myresolver.acme.email=postmaster@example.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
```

did someone have a working example?
