### DISCUSSION TITLE
roles/module checkout with Semaphore

### DISCUSSION THREAD

**Discussion by stafwag** [semaphoreui/semaphore#1941] [Q&A]
Hi,

I do like to concept of Semaphore and its features.

.. But I'm looking for a way to perform a component checkout with authentication.

semaphore has support to execute an ansible which is great, but this doesn't reuse the git authentication method (e.g. private key/ssh config.)

Example:

```
roles/requirements.yml:

---
# https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#installing-roles-and-collections-from-the-same-requirements-yml-file
- name: myrole
 scm: git
 src: git@mygit:myspace/mybranch/myrepo.git
 version: main
``` 

But this doesn't reuse the SSH authentication method in Semaphore.

A possible solution is to use the access token (if you're using GitLab/GitHub) but it makes sense to reuse the existing authentication.

The only solution that I found is not to use the internal Semaphore Key Store and set up the authentication outside of Semaphore;

Set up a "fake key"  of Type "none" in the semaphore Key Store.
Create an SSH config and mount it inside the semaphore container. 

Is there a way with Semaphore to reuse the SSH config that is already set up to perform the git clone for the roles requirements.yml install?

This question is somewhat related to:

https://github.com/semaphoreui/semaphore/discussions/847
https://github.com/semaphoreui/semaphore/discussions/1191

Another solution is to use git submodules, I tested it and as far as I can see Semaphore doesn't allow to perform a git submodule checkout.

https://github.com/semaphoreui/semaphore/issues/525

Is a git submodule checkout on the Semaphore roadmap?
