### DISCUSSION TITLE
Semaphore with SSH proxy

### DISCUSSION THREAD

**Discussion by lpleao** [semaphoreui/semaphore#1993] [Q&A]
Hello,

Does anyone knows if Semaphore will work with an inventory with a variable like this:
 ansible_ssh_common_args: '-o ProxyCommand="ssh -p 22222 -i /sshproxy/sshproxy.key user@sshproxy nc %h %p"'

or:
 ansible_ssh_common_args: '-o ProxyCommand="ssh -p 22222 -i /sshproxy/sshproxy.key -W %h:%h user@sshproxy"'

I tried and the execution of the task just hangs... the same commands given to the shell work flawlessly...

I'm running the official Docker container version 2.9.75.

**Comment by tl87** [comment]
I have not gotten it to work. So I'm also interested if anyone has this working?

I've tried multiple things, like trying to set proxyjump up in the ansible inventory:

```yaml
bastion:
  vars:
    ansible_connetion: ssh
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: username
    ansible_port: 22
  hosts:
    proxyhost.lan:
      ansible_host: proxyhost.lan

servers:
  vars:
    ansible_connection: ssh
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: username
    ansible_port: 22
    ansible_common_args: '-o ProxyCommand="ssh -W %h:%p -q username@proxyhost.lan"'
  hosts:
    host1.com:
      ansible_host: host1.com
    host2.com:
      ansible_host: host2.com
```
