### DISCUSSION TITLE
Semaphore in Podman stopped working

### DISCUSSION THREAD

**Discussion by Pshemas** [semaphoreui/semaphore#2066] [Q&A] [answered]
After a server restart I can't get Semaphore start again in Podman container. I get this in the logs:

```
/usr/local/bin/server-wrapper: source: line 184: can't open './venv/bin/activate': No such file or directory
```

I've tried mapping more folders etc - still I can't get it to work again.

Here's the section for SempahoreUI from compose.yaml file:

```yaml
  semaphore:
    restart: unless-stopped
    image: semaphoreui/semaphore:latest
    name: semaphore
    user: $UID:$UID
    env_file:
      - $PWD/.ENV/.semaphore
    networks:
      - caddynet
      - semnet
    volumes:
      - $PWD/semaphore/semaphore-data:/etc/semaphore:z
      - $PWD/semaphore/semaphore-temp:/tmp/semaphore:z
      - $PWD/semaphore/semaphore-home:/home/semaphore:z
      - $PWD/semaphore/semaphore-venv:/opt/semaphore/venv:z

```
