### DISCUSSION TITLE
Problem: connect to LDAP/LDAPS from Docker

### DISCUSSION THREAD

**Discussion by akupreev** [semaphoreui/semaphore#2106] [Q&A]
### Issue

Colleagues, good afternoon.
I encountered a problem enabling LDAP/LDAPS authorization in semaphore.
Semaphore is deployed in docker-container using docker-compose, when deployed, the config.json configuration is not pulled from the compose.yml file, namely, the configuration from the SEMAPHORE_LDAP_MAPPING_* values ​​is not pulled up.
Configuration example:

SEMAPHORE_LDAP_ACTIVATED: "yes"
SEMAPHORE_LDAP_HOST: "example.com"
SEMAPHORE_LDAP_PORT: "636"
SEMAPHORE_LDAP_DN_BIND: "cn=test,ou=service,ou=Accounts,ou=Organization,dc=example,dc=com"
SEMAPHORE_LDAP_PASSWORD: "secret-password"
SEMAPHORE_LDAP_DN_SEARCH: "dc=example,dc=com"
SEMAPHORE_LDAP_NEEDTLS: "yes"
SEMAPHORE_LDAP_SEARCH_FILTER: "(&(sAMAccountName=%s)(memberOf=ou=Users,ou=Organization,dc=example,dc=com))"
SEMAPHORE_LDAP_MAPPING_DN: "dn"
SEMAPHORE_LDAP_MAPPING_MAIL: "{{userPrincipalName}}@example.com"
SEMAPHORE_LDAP_MAPPING_UID: "sAMAccountName"
SEMAPHORE_LDAP_MAPPING_CN: "cn"

Tell me please where I made a mistake?

### Impact

Docker

### Installation method

Docker

### Database

Postgres

### Browser

Chrome

### Semaphore Version

2.9.112

**Comment by fiftin** [comment]
We have examples how to config LDAP:

https://github.com/semaphoreui/semaphore/tree/develop/examples/openldap

**Comment by akupreev** [comment]
Good afternoon.
Do I understand correctly that the variables below are not required?

SEMAPHORE_LDAP_MAPPING_DN: "dn"
SEMAPHORE_LDAP_MAPPING_MAIL: "{{userPrincipalName}}@example.com"
SEMAPHORE_LDAP_MAPPING_UID: "sAMAccountName"
SEMAPHORE_LDAP_MAPPING_CN: "cn"

Also, please clarify, do I understand correctly that semaphore only works with OpenLdap, and connecting to Microsoft Active Directory is impossible?

**Reply by tboerger** [reply]
Active directory should also work, but it's simply not tested automatically. AFAIK there are people in the community using it with an AD.

**Comment by MadsMMP** [comment]
Did you find a solution? Currently have similar problem. I do not get any logs to why LDAP isnt working.

Also using Docker Compose

**Comment by akupreev** [comment]
@MadsMMP Hello my friend. At the moment, I have not found a suitable solution to make the LDAP Semaphore with AD connection work.

**Reply by MadsMMP** [reply]
I have found a solution!

The docker-compse.yml configuration doesn't match the original config.json which it meant to be used.

Therfore u need to create a config.json and make it use that instead of the arguments in the compose file.

Please tell me if you need more depth explanation

**Reply by vtpham** [reply]
> solution

Hi MadsMMP 
could you provide a more detailed solution on how to fix it. - many Thx

**Comment by 00shorty** [comment]
Hi all,

we do have the same problem here as well with LDAP.
Using docker with local users is working fine but when we enable LDAP support nothing is working the container won't come up
 

>      SEMAPHORE_LDAP_ACTIVATED: "yes"
>     SEMAPHORE_LDAP_HOST: "domaincontroller.secure.local"
>      SEMAPHORE_LDAP_PORT: "636"
>      SEMAPHORE_LDAP_DN_BIND: "CN=Technical User 0040,OU=Service Accounts,DC=secure,DC=local"
>      SEMAPHORE_LDAP_PASSWORD: "Super$ecurePa$$word"
>      SEMAPHORE_LDAP_DN_SEARCH: "dc=secure,dc=local"
>      SEMAPHORE_LDAP_NEEDTLS: "yes"
>      SEMAPHORE_LDAP_SEARCH_FILTER: "(&(sAMAccountName=%s)(memberOf=CN=Semaphore_admin,OU=Permissions,DC=secure,DC=local))"
>      SEMAPHORE_LDAP_MAPPING_DN: "dn"
>      SEMAPHORE_LDAP_MAPPING_MAIL: "sAMAccountName"
>      SEMAPHORE_LDAP_MAPPING_UID: "sAMAccountName"
>      SEMAPHORE_LDAP_MAPPING_CN: "cn"


Error Message


>      semaphore-1  | 
>      semaphore-1  | Hello! You will now be guided through a setup to:
>      semaphore-1  | 
>      semaphore-1  | 1. Set up configuration for a MySQL/MariaDB database
>      semaphore-1  | 2. Set up a path for your playbooks (auto-created)
>      semaphore-1  | 3. Run database Migrations
>      semaphore-1  | 4. Set up initial semaphore user & password
>      semaphore-1  | 
>      semaphore-1  | What database to use:
>      semaphore-1  |    1 - MySQL
>      semaphore-1  |    2 - BoltDB
>      semaphore-1  |    3 - PostgreSQL
>      semaphore-1  |  (default 1): 
>      semaphore-1  | db Hostname (default 127.0.0.1:3306): 
>      semaphore-1  | db User (default root): 
>      semaphore-1  | db Password: 
>      semaphore-1  | time="2024-11-27T10:51:52+01:00" level=warning msg="An input error occurred: expected newline"
>      semaphore-1  | time="2024-11-27T10:51:52+01:00" level=warning msg="An input error occurred: expected newline"
>      semaphore-1  | time="2024-11-27T10:51:52+01:00" level=warning msg="An input error occurred: expected newline"
>      semaphore-1  | db Name (default semaphore): 
>      semaphore-1  | Playbook path (default /tmp/semaphore): 
>      semaphore-1  | Public URL (optional, example: https://example.com/semaphore): 
>      semaphore-1  | Enable email alerts? (yes/no) (default no): 
>      semaphore-1  | Enable telegram alerts? (yes/no) (default no): 
>      semaphore-1  | Enable slack alerts? (yes/no) (default no): 
>      semaphore-1  | Enable Rocket.Chat alerts? (yes/no) (default no): 
>      semaphore-1  | Enable Microsoft Team Channel alerts? (yes/no) (default no): 
>      semaphore-1  | Enable LDAP authentication? (yes/no) (default no): 
>      semaphore-1  | LDAP server host (default localhost:389): 
>      semaphore-1  | Enable LDAP TLS connection (yes/no) (default no): 
>      semaphore-1  | LDAP DN for bind (default cn=user,ou=users,dc=example): 
>      semaphore-1  | Password for LDAP bind user (default pa55w0rd): 
>      semaphore-1  | LDAP DN for user search (default ou=users,dc=example): 
>      semaphore-1  | LDAP search filter (default (uid=%s)): 
>      semaphore-1  | LDAP mapping for DN field (default dn): 
>      semaphore-1  | LDAP mapping for username field (default uid): 
>      semaphore-1  | LDAP mapping for full name field (default cn): 
>      semaphore-1  | LDAP mapping for email field (default mail): 
>      semaphore-1  | Config output directory (default /home/semaphore): 
>      semaphore-1  | Running: mkdir -p uid..
>      semaphore-1  | Configuration written to uid/config.json..
>      semaphore-1  | Loading config
>      semaphore-1  | Validating config
>      semaphore-1  |  Pinging db..
>      semaphore-1  | Running db Migrations..
>      semaphore-1  | 
>      semaphore-1  | 
>      semaphore-1  |  > Username:  > Email: 
>      semaphore-1  |  Welcome back, /etc/semaphore! (a user with this username/email is already set up..)
>      semaphore-1  | 
>      semaphore-1  |  Re-launch this program pointing to the configuration file
>      semaphore-1  | 
>      semaphore-1  | ./semaphore server --config uid/config.json
>      semaphore-1  | 
>      semaphore-1  |  To run as daemon:
>      semaphore-1  | 
>      semaphore-1  | nohup ./semaphore server --config uid/config.json &
>      semaphore-1  | 
>      semaphore-1  |  You can login with mail or cn.
>      semaphore-1  | No additional python dependencies to install
>      semaphore-1  | Starting semaphore server
>      semaphore-1  | Loading config
>      semaphore-1  | Cannot Find configuration! Use --config parameter to point to a JSON file generated by `semaphore setup`.
>      semaphore-1  | 
>      semaphore-1  | 
>      semaphore-1  |  > Username:  > Email: 
>      semaphore-1  |  Welcome back, /etc/semaphore! (a user with this username/email is already set up..)
>      semaphore-1  | 
>      semaphore-1  |  Re-launch this program pointing to the configuration file
>      semaphore-1  | 


00Shorty

**Reply by 00shorty** [reply]
I resolved it by using the following configurator: https://semaphoreui.com/install/docker/2_10_42/

**Comment by msultanov** [comment]
Same issue here -> https://github.com/semaphoreui/semaphore/issues/1370

The issue still exists in the current version (2.16.45)
I'm trying to pass LDAP settings using environment variables in Docker Swarm container
As a LDAP i'm using Microsoft Active Directory

```
services:
  semaphore:
    image: semaphoreui/semaphore:latest
    hostname: semaphore
    environment:
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: ************
      SEMAPHORE_DB_HOST: mysql.corp.company.com
      SEMAPHORE_DB_PORT: 3306
      SEMAPHORE_DB_DIALECT: mysql
      SEMAPHORE_DB: Semaphore
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_NAME: Admin
      SEMAPHORE_ADMIN_EMAIL: it@company.com
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ADMIN_PASSWORD: ************
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: ************
      SEMAPHORE_LDAP_ACTIVATED: yes
      SEMAPHORE_LDAP_HOST: ad1-dc1.corp.company.com
      SEMAPHORE_LDAP_PORT: 389
      SEMAPHORE_LDAP_NEEDTLS: 'false'
      SEMAPHORE_LDAP_DN_BIND: CN=Semaphore Bind,OU=Service Users,DC=corp,DC=company,DC=com
      SEMAPHORE_LDAP_PASSWORD: ************
      SEMAPHORE_LDAP_DN_SEARCH: OU=Company Users,DC=corp,DC=company,DC=com
      SEMAPHORE_LDAP_SEARCH_FILTER: (&(objectClass=organizationalPerson)(sAMAccountName=%s))
      TZ: UTC
    networks:
      - traefik_global
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_global"
        - "traefik.http.routers.semaphore.rule=Host(`semaphore.corp.company.com`)"
        - "traefik.http.routers.semaphore.entrypoints=web"
        - "traefik.http.routers.semaphore.service=semaphore-svc"
        - "traefik.http.services.semaphore-svc.loadbalancer.server.port=3000"
networks:
  traefik_global:
    external: true
```

As you can see, there are some whitespaces in BIND_DN and SEARCH_DN variables. And when I run the service, it starts with errors 

```
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    |
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | Hello! You will now be guided through a setup to:
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    |
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | 1. Set up configuration for a MySQL/MariaDB database
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | 2. Set up a path for your playbooks (auto-created)
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | 3. Run database Migrations
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | 4. Set up initial semaphore user & password
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    |
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | What database to use:
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    |    1 - MySQL
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    |    2 - BoltDB (DEPRECATED!!!)
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    |    3 - PostgreSQL
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    |    4 - SQLite
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    |  (default 1):
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | db Hostname (default 127.0.0.1:3306):
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | db User (default root):
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | db Password:
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | db Name (default semaphore):
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | Playbook path (default /tmp/semaphore):
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | time="2025-12-15T16:52:23Z" level=warning msg="An input error occurred: expected newline"
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | time="2025-12-15T16:52:23Z" level=warning msg="An input error occurred: expected newline"
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | time="2025-12-15T16:52:23Z" level=warning msg="An input error occurred: expected newline"
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | time="2025-12-15T16:52:23Z" level=warning msg="An input error occurred: expected newline"
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | Public URL (optional, example: https://example.com/semaphore):
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | Enable email alerts? (yes/no) (default no):
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | Enable telegram alerts? (yes/no) (default no):
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | Enable slack alerts? (yes/no) (default no):
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | Enable Rocket.Chat alerts? (yes/no) (default no):
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | Enable Microsoft Team Channel alerts? (yes/no) (default no):
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | Enable LDAP authentication? (yes/no) (default no):
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | LDAP server host (default localhost:389):
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | Enable LDAP TLS connection (yes/no) (default no):
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | LDAP DN for bind (default cn=user,ou=users,dc=example):
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | Password for LDAP bind user (default pa55w0rd):
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | LDAP DN for user search (default ou=users,dc=example):
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | LDAP search filter (default (uid=%s)):
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | LDAP mapping for DN field (default dn):
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | LDAP mapping for username field (default uid):
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | LDAP mapping for full name field (default cn):
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | LDAP mapping for email field (default mail):
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | Config output directory (default /home/semaphore):
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | Running: mkdir -p dn..
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | Configuration written to dn/config.json..
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | Loading config
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | Validating config
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    |  Pinging db..
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | Running db Migrations..
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    |
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    |
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    |  > Username:  > Email:
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    |  Welcome back, mail! (a user with this username/email is already set up..)
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    |
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    |  Re-launch this program pointing to the configuration file
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    |
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | ./semaphore server --config dn/config.json
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    |
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    |  To run as daemon:
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    |
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | nohup ./semaphore server --config dn/config.json &
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    |
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    |  You can login with cn or uid.
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | No additional python dependencies to install
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | Starting semaphore server
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | Loading config
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | Cannot Find configuration! Use --config parameter to point to a JSON file generated by `semaphore setup`.
``` 

The exact errors are here 

``` 
time="2025-12-15T16:52:23Z" level=warning msg="An input error occurred: expected newline"
time="2025-12-15T16:52:23Z" level=warning msg="An input error occurred: expected newline"
time="2025-12-15T16:52:23Z" level=warning msg="An input error occurred: expected newline"
time="2025-12-15T16:52:23Z" level=warning msg="An input error occurred: expected newline"
``` 

It is even writing the config in the incorrect folder
>> Configuration written to dn/config.json..
