### DISCUSSION TITLE
Inventory with multiple keys and groups

### DISCUSSION THREAD

**Discussion by oliverjm32** [semaphoreui/semaphore#2142] [Q&A]
Hello,

New to Semaphore UI and liking the look of it so far! :) I've got an existing inventory and looking to do one of two things, either move the whole inventory in to semaphore or move just the passwords in the semaphores key storage. 

My main issue with moving over the inventory to semaphore UI is that i use groups and within the groups sometimes each host has different credentials (see zfs_servers in example below), from what i can see there isnt a way to replicate this in semaphore? 

This lead me to just storing the passwords in the keystore but I cannot see a way of referencing the key store in my inventory file unless I'm missing something? 

Also ideally i want to be using SSH keys but that obviously has the same issues currently

Inventory file example:

```
zfs_servers:
  hosts:
    zfs-host1:
      ansible_user: root
      ansible_password: *** pass ***
    zfs-host2:
      ansible_user: ansible
      ansible_password: *** pass2 ***
ipa_servers:
  hosts:
    ipa-host1:
    ipa-host2:
  vars:
    ansible_user: ansible
    ansible_password: *** pass2 ***
ipa_joined_servers:
  hosts:
    ipa-host1:
    ipa-host2:
    zfs-host2:
    app-server:
  vars:
    ansible_user: ansible
    ansible_password: *** pass2 ***
``` 

Also on a separate topic, is there any plan to allow bash tasks to use inventory to remotely connect to a server and run said bash task?
