### DISCUSSION TITLE
Semaphore Runners in Docker

### DISCUSSION THREAD

**Discussion by Ovsyank** [semaphoreui/semaphore#2173] [Q&A]
Good afternoon. 

I decided to try setting up playbooks ansible to run via runners. I turned to the documentation on the official website. 
I tried to implement the semaphore ansible server in runners mode and connect a runner that was raised in docker on another server. 
There are problems getting runner to work with the server.

runner compose.yml:
```
networks:
  test:
   driver: bridge

services:
  runner:
    container_name: smp-runner
    image: semaphoreui/runner:v2.10.13-beta
    volumes:
      - ./config.json:/etc/semaphore/config.json
    restart: unless-stopped
    networks:
      - test
```
Logs:
```
Starting semaphore runner
Loading config
Validating config
time="2024-07-05T08:47:14Z" level=info msg="Attempting to register on the server"
time="2024-07-05T08:47:14Z" level=info msg="Registering a new runner"
time="2024-07-05T08:47:14Z" level=info msg="The runner has been started"
```
config.json:
```
{
  "runner": {
    "registration_token": "secret-password",
    "config_file": "/tmp/semaphore/runner.config_file",
    "api_url": "http://ipaddress:3002/api",
    "max_parallel_tasks": 10
  }
}
```
Semaphore Ansible Server 
In the config.json configuration file I changed the parameters:
```
---
"runner_registration_token": "secret-password",
"use_remote_runner": true,
---
```

After the start, it is clear that the runner does not register on the server using the created token. There is network accessibility between the Semaphore server and the runner

Even when accessing the URL "http://ipaddress:3002/api" the page and request are returned "Not found"

I read various requests in the Issues and Discussions sections, but I could not find an answer to the question. What am I doing wrong?
