### DISCUSSION TITLE
Integration Extract JSON Value

### DISCUSSION THREAD

**Discussion by ronzyfonzy** [semaphoreui/semaphore#2350] [General]
Hello 👋 

Before I ask the question I have to say that this is an awesome project 👍  ... so Thank You

I have deployed Semaphore on my staging server and I created an Integration where a webhook (PullRequest created) from Bitbucket triggers a ansible task. The problem I have is that I am unable to extract the branch name from the POST request. Nowhere in the documentation I have found how to exactly extract a nested value in a JSON payload. I presume I can do that with JSONPath syntaxs. In my case that is `pullrequest.source.branch.name` (based on the [payload](https://support.atlassian.com/bitbucket-cloud/docs/event-payloads/#Pull-request) - see sample payload bellow)

Am I doing something wrong? Should I extract in another way? 

This is an obfuscated JSON example:
```json
{
  "pullrequest": {
    "comment_count": 0,
    "task_count": 0,
    "type": "pullrequest",
    "id": 1017,
    "title": "Feature/FLEX-7202 ansible",
    "description": "",
    "source": {
      "branch": {
        "name": "feature/FLEX-7202-ansible",
        "links": {}
      },
      "commit": {},
      "repository": {}
    },
    "reviewers": [],
    "participants": [],
    "links": {}
  }
}
```

This is how I have setup my value extractor:

![CleanShot 2024-09-19 at 09 30 36@2x](https://github.com/user-attachments/assets/12999e34-df2a-47e8-871b-f1d5ad0dadb7)

**Comment by ronzyfonzy** [comment]
Additionally ... What is interesting is that I also have a Matcher set up the same way. So if the branch name contains `FLEX-` string the task should be executed. So it seems it does find the key in the matcher, but doesn't extract it the right way in the extractor?
![CleanShot 2024-09-19 at 12 15 16@2x](https://github.com/user-attachments/assets/06614bf0-8f1a-4079-83d8-65efa32e6ecd)

**Comment by ronzyfonzy** [comment]
Ow and this is how I extract the env value in my task
```yaml
---
- hosts: name_flex_dev_01
  vars:
    branch: "{{ lookup('env', 'FLEX_BRANCH', default='develop') }}"
  become: yes
  become_user: ubuntu

  tasks:
    - name: output branch
      debug:
        msg: "branch={{ branch }}"

````

**Comment by ronzyfonzy** [comment]
So I started debugging the app and got to this LocalJob. It seems the issue is occurring because the t.Environment.ENV value might not be in a proper JSON format, or the json.Unmarshal call is not correctly parsing the input.
https://github.com/semaphoreui/semaphore/blob/f5404b17b086220ccee0da54a80f4980e0f3efd1/services/tasks/LocalJob.go#L152-L156

I added some outputs to the CLI and saw that `api/integration.go` parses the JSON body correctly but then this `getEnvironmentENV` function returns an empty result

**Comment by fiftin** [comment]
Hi @ronzyfonzy  
you can use variables following way:

```yaml
---
- hosts: name_flex_dev_01
  vars:
    branch: "{{ FLEX_BRANCH }}"
  become: yes
  become_user: ubuntu

  tasks:
    - name: output branch
      debug:
        msg: "branch={{ branch }}"
```

**Reply by ronzyfonzy** [reply]
Thank you @fiftin that worked at the end.

Another thing that I am currently checking is how to extract a JSON value from an array. So I have my bitbucket webhooks set and I want to run a task just for specific target branches. I don't know if I am doing something wrong or extraction from an array is not supported yet.

So in the integration I have this ExtractValue (I also tryed with all uppercase BITBUCKET_BRANCH for the variable name)

![CleanShot 2025-04-30 at 08 33 32@2x](https://github.com/user-attachments/assets/d823c928-c5d6-4e8b-beaa-e8bbd954f9a6)

And this is an example JSON body payload
```json
{
  "push": {
    "changes": [
      {
        "old": {
          "name": "feature/a-sample-branch",
          "type": "branch"
        },
        "new": {
          "name": "feature/a-sample-branch",
          "type": "branch"
        }
      }
    ]
  }
}
```

This is the gist of my playbook

```yaml
---
- hosts: all
  vars:
    bitbucket_branch: "{{ lookup('env', 'BITBUCKET_BRANCH', default='') }}"
    bitbucket_branch_allowed: "{{ lookup('env', 'BITBUCKET_BRANCH_ALLOWED', default='develop') }}"

  pre_tasks:
    - name: Display deployment information
      debug:
        msg: |
          Deploying background workers:
            Bitbucket Branch: {{ bitbucket_branch }}
            Allowed Branch: {{ bitbucket_branch_allowed }}

    - name: End play if bitbucket branch is not allowed
      meta: end_play
      when: bitbucket_branch != '' and bitbucket_branch != bitbucket_branch_allowed
```

When the webhook is triggered I see this in Semaphore
```
TASK [Display deployment information] ******************************************
ok: [xxx] =>
  msg: |-
    Deploying background workers:
      Bitbucket Branch: <nil>
      Allowed Branch: develop
TASK [End play if bitbucket branch is not allowed] *****************************
```
