### DISCUSSION TITLE
How do i use a proxy when semaphore connects to github

### DISCUSSION THREAD

**Discussion by pemca** [semaphoreui/semaphore#2691] [Q&A]
Hi
I have semaphore ui on a small vm and defined a access key (with my private key) to my github and a repository using that access key,
and it works fine. 
In another setup i must connect to github via an outbound proxy. Where do i define the same as an ssh ProxyJump config file ?

**Comment by juju4** [comment]
I did not found an option to do it from semaphore but in my setup provisioning, I deploy the needed ssh_config for semaphore user along ssh key and restricted authorization
```
    - name: Ensure semaphore .ssh dir exists
      ansible.builtin.file:
        path: "{{ semaphore_home }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ semaphore_user }}"
    - name: Generate an OpenSSH keypair for semaphore
      community.crypto.openssh_keypair:
        path: "{{ semaphore_home }}/.ssh/id_ed25519"
        type: ed25519
        mode: '0600'
        owner: "{{ semaphore_user }}"
    - name: Configure semaphore ssh with Proxyjump
      ansible.builtin.copy:
        content: |
          Host SSH_JUMPHOST
            Hostname SSH_JUMPHOST_IP
            User SSH_JUMPHOST_USER
            IdentityFile {{ semaphore_home }}/.ssh/id_ed25519
          Host github.com
            ProxyJump SSH_JUMPHOST
        dest: "{{ semaphore_home }}/.ssh/config"
        mode: '0600'
        owner: "{{ semaphore_user }}"
    - name: Get semaphore ssh pubkey
      ansible.builtin.command:
        cmd: "cat {{ semaphore_home }}/.ssh/id_ed25519.pub"
      register: s_key
      changed_when: false
    - name: Set authorized key to SSH_JUMPHOST
      ansible.posix.authorized_key:
        user: SSH_JUMPHOST_USER
        state: present
        key: "{{ s_key.stdout }}"
        key_options: 'from="SEMAPHORE_IP",no-agent-forwarding,no-pty,no-user-rc,no-x11-forwarding,permitopen="github.com:22"'
      delegate_to: SSH_JUMPHOST
    - name: Test github ssh connectivity
      ansible.builtin.command:
        cmd: ssh -T git@github.com
      register: ssh_t_github
      become: yes
      become_user: "{{ semaphore_user }}"
      changed_when: false
      failed_when:
        - "'successfully authenticated, but GitHub does not provide shell access.' not in ssh_t_github.stderr"
        - ssh_t_github.rc != 0

```
