### DISCUSSION TITLE
How to get emails to work in docker-compose environment?

### DISCUSSION THREAD

**Discussion by itsamemarkus** [semaphoreui/semaphore#2943] [Q&A]
Hi, I installed semaphore for the first time, tested a bunch without email env variables, added the email config to my `docker-compose.yml`

```yaml
services:
    semaphore:
        ports:
          - 127.0.0.1:3000:3000
        image: semaphoreui/semaphore:v2.13.12-powershell7.5.0
        environment:
            SEMAPHORE_DB_DIALECT: bolt
            SEMAPHORE_ADMIN: myusername
            SEMAPHORE_ADMIN_PASSWORD: abc
            SEMAPHORE_ADMIN_NAME: MyName
            SEMAPHORE_ADMIN_EMAIL: my@email.tld
            # SEMAPHORE_USE_REMOTE_RUNNER: "True"
            # SEMAPHORE_RUNNER_REGISTRATION_TOKEN: "cba"
            SEMAPHORE_EMAIL_SENDER: "ansible@mydomain.tld"
            SEMAPHORE_EMAIL_HOST: "mail.mydomain.tld"
            SEMAPHORE_EMAIL_PORT: "587"
            SEMAPHORE_EMAIL_USERNAME: "ansible@mydomain.tld"
            SEMAPHORE_EMAIL_PASSWORD: "xyz"
            SEMAPHORE_EMAIL_SECURE: "True"
        volumes:
            - semaphore_data:/var/lib/semaphore
            - semaphore_config:/etc/semaphore
            - semaphore_tmp:/tmp/semaphore
volumes:
    semaphore_data:
    semaphore_config:
    semaphore_tmp:
```

My user is allowed to send alerts (small complaint here if a dev is reading: Please make the permission for owners to send alerts default, imo is not intuitive that this has to be enabled)

![Screenshot 2025-04-20 at 14 24 10@2x](https://github.com/user-attachments/assets/1ee5600f-f4a5-4760-af72-89e91ba3750c)

When I exec into the container all environment variables are present when executing `printenv`

The config file inside the container looks like this:

```
/etc/semaphore $ cat config.json
{
 	"bolt": {
 		"host": "/var/lib/semaphore/database.boltdb"
 	},
 	"dialect": "bolt",
 	"tmp_path": "/tmp/semaphore",
 	"cookie_hash": "sdf",
 	"cookie_encryption": "dfs",
 	"access_key_encryption": "ggf"
}
```

After reading https://docs.semaphoreui.com/administration-guide/configuration/ I thought just adding the environment variables to my `docker-compose.yml` afterwards would suffice.

On my firewall I can't see any connection attempt to my mailserver. I can manually ping the mailserver from the container and get replies. Am I missing something? Settings or so? 

**Edit**
~Or do the environment variables for the email server config have to be present with the very first run?~
I removed all volumes and strated from scratch with the email environment variables. There is no attempt to send an email. 

Might even be a bug? Manual connection to my mailserver works from within the semaphore container 
![Screenshot 2025-04-20 at 14 55 11](https://github.com/user-attachments/assets/a248e950-b128-41ee-b8e5-964c2b8256ba)

**Comment by fiftin** [comment]
Hi @itsamemarkus ,

1) I recommend you to use container configurator https://semaphoreui.com/install/docker/2_13/

    <img width="500" alt="image" src="https://github.com/user-attachments/assets/c5d762cb-cc26-4cde-8965-9aa8fab5c825" />
2) To get email notifications, you need:
    1) Set up SMTP server (you did)
    2) Enable notifications for a user:
    
        <img width="300" alt="image" src="https://github.com/user-attachments/assets/b5da2617-35b7-4b05-bccd-0006e8a03283" />
    3) Enable notifications for a project:
    
         <img width="300" alt="image" src="https://github.com/user-attachments/assets/f050cc80-7289-44e4-84ce-451552ff71c8" />

**Reply by itsamemarkus** [reply]
hi @fiftin , thank you very much for your reply. I tested this again and used the configurator. Unfortunately I can't see sempaphore trying to establish a connection to my mailserver.

This time I used `semaphoreui/semaphore:v2.13.12` because I thought maybe something is off with the powershell image, but it's the same behavior.

Did this, just my real data (in the exact same format)

![Screenshot 2025-04-20 at 17 40 02@2x](https://github.com/user-attachments/assets/9a6e9734-dd1d-4f6f-9eb1-7507212d2722)


![Screenshot 2025-04-20 at 17 39 50@2x](https://github.com/user-attachments/assets/9f5aafae-ae52-422e-9825-cdd58eec4085)

resulting in

```yaml
services:
    semaphore:
        ports:
            - 3000:3000
        image: semaphoreui/semaphore:v2.13.12
        environment:
            SEMAPHORE_DB_DIALECT: bolt
            SEMAPHORE_ADMIN: myname
            SEMAPHORE_ADMIN_PASSWORD: adminpw
            SEMAPHORE_ADMIN_NAME: MyName
            SEMAPHORE_ADMIN_EMAIL: my@anotherdomain.tld
            SEMAPHORE_EMAIL_SENDER: "ansible@mydomain.tld"
            SEMAPHORE_EMAIL_HOST: "mail.mydomain.tld"
            SEMAPHORE_EMAIL_PORT: "587"
            SEMAPHORE_EMAIL_USERNAME: "ansible@mydomain.tld"
            SEMAPHORE_EMAIL_PASSWORD: "myemailpassword"
            SEMAPHORE_EMAIL_SECURE: "True"
```

- Send alerts for my user is enabled
- Allow alerts for this project is enabled

The server logs aren't very verbose, don't see any log entry about an attenmpt to send an email
