### DISCUSSION TITLE
Playbook works from terminal but fails when using SemaphoreUI

### DISCUSSION THREAD

**Discussion by Mailstorm-ctrl** [semaphoreui/semaphore#3073] [Q&A]
I have a fairly simply playbook that will update DHCP reservations based on information passed to semaphore. 

```YAML
    - name: Assign DHCP reservation
      community.windows.win_dhcp_lease:
        type: reservation
        ip: "{{ IP_ADDR }}"
        scope_id: "{{ IP_PREFIX }}"
        mac: "{{ MAC_ADDR }}"
        dns_hostname: "{{ DNS_HOSTNAME }}"
        reservation_name: "{{ DNS_HOSTNAME }}"
        description: "Reservation managed by ansible/netbox"
        state: present
      when: "ADDRESERVATION | bool and 'service-primary' in hostvars[inventory_hostname].tags"
    
    - name: Remove DHCP Reservation
      community.windows.win_dhcp_lease:
        ip: "{{ IP_ADDR }}"
        state: absent
      when: "not ADDRESERVATION | bool and 'service-primary' in hostvars[inventory_hostname].tags"

    - name: Wait for DHCP to process reservation before replication
      ansible.builtin.wait_for:
        timeout: 5
      delegate_to: localhost

    - name: Replicate DHCP Reservations
      ansible.windows.win_shell: |
        Invoke-DhcpServerv4FailoverReplication -ScopeId {{ IP_PREFIX }} -Force
      when: "'service-primary' in hostvars[inventory_hostname].tags"
```

All of these tasks work when run from semaphore EXCEPT the last one. The last one complains about a permission issue. It's a permission issue reported by a DHCP server.

Now, when I run this _**exact same playbook**_ with the **_exact same inventory_** directly from the **_same ansible server_** using the **_same environment_**...it works. The final task completes with no permission or access issues. What is happening inside of semaphore that is changing the behavior of my task?
