### DISCUSSION TITLE
use ssh private key from KeyStore

### DISCUSSION THREAD

**Discussion by Korhm** [semaphoreui/semaphore#847] [Q&A] [answered]
Hello,

I would like use an ssh key to connect to remote hosts, that is stored is the Key Store of Sempahore (like to one to connect to git).
Is it something possible ?

**Comment by fiftin** [comment]
Yes, you can.

**Comment by Korhm** [comment]
Thank you for the answer fiftin, but can you please elaboration on how to do it ?

On the Template Edit form, I do not find any way to select an ssh key from the KeyStore. The only thing about it is inside the "Advanced" field, but the key has to come from file system, not database

**Reply by fiftin** [reply]
It should be specified in the Inventory settings.

<img width=300 src="https://user-images.githubusercontent.com/914224/152339757-9f0528d7-287a-45fd-a9a5-6ac34fac3659.png" />

**Comment by Korhm** [comment]
The ssh key is set in the inventory, but it seems that ansible won't use it for the ssh connection to remote host.
Semaphore creates `/tmp/semaphore/access_key_736139256` (which is deleted after the Play is terminated), but it still uses `/tmp/semaphore/.ssh/id_rsa` that does not exist...

In the debug log of the task run, I have :
```
5:06:26 PM
PLAYBOOK: copy_cert.yml ********************************************************
5:06:26 PM
Positional arguments: tasks/copy_file.yml
5:06:26 PM
verbosity: 4
5:06:26 PM
private_key_file: /tmp/semaphore/access_key_736139256
5:06:26 PM
connection: smart
5:06:26 PM
timeout: 10
5:06:26 PM
become_method: sudo

[...]

5:06:26 PM
TASK [Copy file] ***********************************************
5:06:26 PM
task path: /tmp/semaphore/repository_1_1/tasks/copy_file.yml:7
5:06:26 PM
<lab-server1> ESTABLISH SSH CONNECTION FOR USER: lab-user1
5:06:26 PM
<lab-server1> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/tmp/semaphore/.ssh/id_rsa"' -o KbdInteractiveAuthentication=no -o
```

**Reply by fiftin** [reply]
Latest version uses ssh-agent instead of file.

**Comment by fiftin** [comment]
Hi @Korhm,

Looks like you should specify username for your remote server(s).

You can do it via Environments:

<img width=400 src="https://user-images.githubusercontent.com/914224/152654844-a32ce6d7-ebf8-47be-b8d3-378597c3850a.png">

Since this is not very convenient, I added the ability to set a username in Access Key settings. It will be available in next release:

<img width=400 src="https://user-images.githubusercontent.com/914224/152654895-a468082b-b3de-4465-9c8e-1cdf49187a74.png">

**Reply by fiftin** [reply]
Available in [v2.8.45](https://github.com/ansible-semaphore/semaphore/releases/tag/v2.8.45)

**Reply by bor7an** [reply]
Is there option to add environment for different inventory hosts group who are using same SSH key but different SSH users.

![Screenshot_1606](https://github.com/ansible-semaphore/semaphore/assets/159651100/5d6cdabd-18ef-42e7-83a8-d1882a24cb73)
![Screenshot_1607](https://github.com/ansible-semaphore/semaphore/assets/159651100/c7b37e5b-6dda-43e3-aa12-180e5fc89d4f)

**Reply by chakib2002** [reply]
@bor7an did you find a solution? can we assign a unique ssh key for each hosts in an inventory file ?

**Comment by bverkron** [comment]
@fiftin I'm having some difficulty with this as well. It seems semaphore cannot make the connection and throws the following:
`fatal: [nas]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Host key verification failed.", "unreachable": true}`

[debug.log](https://github.com/ansible-semaphore/semaphore/files/9689423/debug.log)

However, I know the key is good because I can use it successfully from my local machine to that server. I have also copied the full SSH command semaphore uses from the debug output and run that locally using my key _and it works_ (after removing the ControlPath option because I don't have that same temp file that semaphore generates)

**SSH command from semaphore debug output**
`ssh -v -C -o ControlMaster=auto -o ControlPersist=60s -o Port=44 -o 'IdentityFile="~/.ssh/id_rsa_nas_maintenance"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="maintenance"' -o ConnectTimeout=10 -tt 192.168.1.219 'touch ~/success.txt'`

**Result on remote host (success.txt file is there)**
```
[maintenance@NAS-219 ~]$ ls -alh
drwxrwxrwx    3 maintena everyone      4.0k Sep 30 20:06 ./
drwxrwxrwx    9 admin    administ      4.0k Sep 30 17:42 ../
-rw-rw----    1 maintena everyone         0 Sep 30 20:06 success.txt
```

So, it seems semaphore isn't using the key correctly or perhaps I don't have some thing setup correctly but I cannot figure out what.

My configuration:
![image](https://user-images.githubusercontent.com/19174503/193384181-b284c9e1-71af-4ca1-bb70-e262fc415d7b.png)

![image](https://user-images.githubusercontent.com/19174503/193384206-60176da3-6a9e-4587-9f41-1a961557af6a.png)

Full contents of inventory file
```
[storage]
nas ansible_host=192.168.1.219 ansible_user=maintenance ansible_port=44
```

![image](https://user-images.githubusercontent.com/19174503/193384234-78371e21-2e6c-4adc-b4ac-ba52e3ac1c52.png)

I'm fairly new to Ansible and semaphore to my apologies if I have something misconfigured.

**Reply by bor7an** [reply]
This options to add ansible_user= next to host working only with first group.

![Screenshot_1608](https://github.com/ansible-semaphore/semaphore/assets/159651100/54a929eb-a319-434c-85a3-806031417f08)
![Screenshot_1609](https://github.com/ansible-semaphore/semaphore/assets/159651100/78654030-00ca-47ff-a90f-9ebdabf1944a)

**Comment by bverkron** [comment]
Interestingly there are a bunch errors related to the `known_hosts` files in the debug log right before it fails. Maybe it's a related?

```
debug1: load_hostkeys: fopen /home/semaphore/.ssh/known_hosts: No such file or directory
debug1: load_hostkeys: fopen /home/semaphore/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug3: hostkeys_find_by_key_hostfile: trying user hostfile "/home/semaphore/.ssh/known_hosts"
debug1: hostkeys_find_by_key_hostfile: hostkeys file /home/semaphore/.ssh/known_hosts does not exist
debug3: hostkeys_find_by_key_hostfile: trying user hostfile "/home/semaphore/.ssh/known_hosts2"
debug1: hostkeys_find_by_key_hostfile: hostkeys file /home/semaphore/.ssh/known_hosts2 does not exist
debug3: hostkeys_find_by_key_hostfile: trying system hostfile "/etc/ssh/ssh_known_hosts"
debug1: hostkeys_find_by_key_hostfile: hostkeys file /etc/ssh/ssh_known_hosts does not exist
debug3: hostkeys_find_by_key_hostfile: trying system hostfile "/etc/ssh/ssh_known_hosts2"
debug1: hostkeys_find_by_key_hostfile: hostkeys file /etc/ssh/ssh_known_hosts2 does not exist
debug1: read_passphrase: can\'t open /dev/tty: No such device or address
Host key verification failed.
```

**Reply by beingyash** [reply]
@Korhm Well, the issue pertains to the known_hosts file only. This file does not exist in the container, hence the ssh key based authentication fails as no known host is available. It works once you manually create this file inside the container in "/home/semaphore/.ssh" and add the public key of the server you were trying to connect with in your playbook.
@fiftin I believe this must be labeled as a bug.

**Comment by bverkron** [comment]
I shelled into the running container (I'm running this in docker via `semaphoreui/semaphore:latest`) and manually created the known_hosts file in the first location it looked and I got past that error but now it's one onto the following error.

`fatal: [nas]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: maintenance@192.168.1.219: Permission denied (publickey,password,keyboard-interactive).", "unreachable": true}`

I see in the job log that it automatically adds bitbucket to know hosts (though not sure where because it doesn't exist where it's looking for the remote ssh server known host. So... why does it not auto-accept known hosts from other servers and where is there no option to get known hosts somewhere?

`Warning: Permanently added 'bitbucket.org' (RSA) to the list of known hosts.`

**Comment by bverkron** [comment]
Final comment for now I switched to a username and password credential for it under Inventory and it works. Just SSH key doesn't

**Comment by thre-z** [comment]
I came across this issue as well, with the same error messages about the `known_hosts` file in the debug output. I ended up finding two solutions: 

1. As root in the Ansible Semaphore instance (in my case a Package manager installation in an LXC), add the host keys by running `ssh host` and accepting the key for each host. This is not ideal as it is manual and the host keys could change. There are probably other, better ways to manage this... but I went with the next option.
2. Disable host key checking in Ansible as described in the docs (https://docs.ansible.com/ansible/latest/user_guide/connection_details.html). This has security implications. In my case, I decided this was worth it for the fix and went this route. 

I hope this ends up being helpful for someone out there.

**Reply by wilpig** [reply]
*2 here for me was the magic ticket.  I just added that to the environment variables like.`{
"ANSIBLE_HOST_KEY_CHECKING": "False"
}`  and everything started connecting just fine.

**Comment by ScarUY** [comment]
I think either google doesn't index this comments, or I'm just awful at googling things, I spent 5 days trying to figure this out and since I could't find it anywhere not even mentioned I assumed it was just me doing something wrong, I tried so many useless thiungs and it turns out it's the feature that doesn't work! Thank you all for posting this here, you've saved my sanity.

**Comment by shallcrm** [comment]
FWIW ... I was experiencing similar symptoms to those reported by @bverkron above, where Semaphore seemed to ignore the SSH private key that I had placed in the Semaphore Key Store.   
Instead, the ssh command was being issued with ...  -o 'IdentityFile="/tmp/semaphore/.ssh/ansible_pwless_ssh_key"' pointing to a local key file that it could not find. 

In my case this was being caused by my playbook having explicitly specified the private key file in a group variable...
   ansible_ssh_private_key_file: ~/.ssh/ansible_pwless_ssh_key

As soon as I removed this explicitly specified variable, Ansible Semaphore correctly used the SSH private key associated with the Inventory and retrieved it from the Key Store.

**Comment by BakermanLP** [comment]
There is another, in my opinion, better solution for that.

Exec into the container and edit the .ssh/config of the user semaphore

```
docker exec -it ansible-semaphore-semaphore-1 sh

mkdir /home/semaphore/.ssh
echo "StrictHostKeyChecking    no" > /home/semaphore/.ssh/config
chown -R semaphore /home/semaphore/.ssh
chmod 700 /home/semaphore/.ssh
chmod 600 /home/semaphore/.ssh/config
```
After that change, the known_hosts file is written and everything works fine.

Could also be changed in the Docker Container Build by editing the /etc/ssh/config file.

**Reply by 0xluc** [reply]
Saved my night, thank you

**Reply by ghost** [reply]
Same here.  I knew I was doing it right and still couldn't figure out why it wouldn't work.  Thanks!

**Reply by heiko-weber** [reply]
awesome hint, took only 5 days to find it ;-)

**Reply by segadora** [reply]
I did this instead

```
services:
  semaphore:
    restart: unless-stopped
    ports:
      - 3000:3000
    image: semaphoreui/semaphore:latest
    command: >
        bash -c "mkdir -p /home/semaphore/.ssh && echo 'StrictHostKeyChecking    no' > /home/semaphore/.ssh/config && chmod 700 /home/semaphore/.ssh && chmod 600 /home/semaphore/.ssh/config && /usr/local/bin/server-wrapper"
....
```

**Comment by kruscho** [comment]
Any solution for that topic? I tried to set up my environment with the ideas of @BakermanLP  and @wilpig , but ended up like @bverkron. User/Password is working, but ssh keys (also adding them manually like @thre-z  described) won´t work.  Am I doing something wrong or is this feature not implemented? 
Log -> [here](https://notebin.de/?0072c896bdb80f3f#Ed2d8PchLjYShWepjTk9s229Zg2itVQdT12hvH1NuSY )

**Reply by BakermanLP** [reply]
If I read the logs correct, there is a passphrase on the ssh key. 
```
debug1: read_passphrase: can't open /dev/tty: No such device or address
```
Try to use a ssh key without a passphrase

**Reply by riker09** [reply]
My private key does _not_ have a passphrase but I'm getting this in the debug logs a well. It did work with your [other solution](https://github.com/ansible-semaphore/semaphore/discussions/847#discussioncomment-6248869), though.

And reading the provided log files it looks like the server accepted the key, but yes, then the passphrase was missing. So I concur that your asessment is correct in this case.

**Reply by fiftin** [reply]
@riker09 do you use snap installation?

**Reply by riker09** [reply]
No, I'm using a containerized install with podman

**Reply by fiftin** [reply]
I just installed Semaphore v2.9.64 from Docker Hub.

I added SSH key with Passphrase. And successfully connected to the server. I need details of your issue.

**Reply by fiftin** [reply]
@riker09 is it Podman installation issue?

**Reply by riker09** [reply]
I will have to investigate that when I find the the time. Unfortunately, it's not a top priority issue (for me). I will report back here, though.

**Comment by ssh30** [comment]
its 2024 this is still a huge issue 

anyways if you are using docker compose to your setup modify it and mount a volume sharing the local server ssh keys
like the way i did 

```
  semaphore:
    restart: unless-stopped
    ports:
      - 3000:3000
    image: semaphoreui/semaphore:latest
    volumes:
      - /home/devops/.ssh/:/home/semaphore/.ssh:ro 
```

**Comment by xremoteuser** [comment]
A year later it still doesn't work.  @ssh30 solution works, but if your user ID is not 1001, copy the ssh dir to another location and make chown 1001:1001

**Reply by fiftin** [reply]
I just installed Semaphore v2.9.64 from Docker Hub.

I added SSH key with Passphrase. And successfully connected to the server. I need details of your issue.

**Comment by jmcamputaro** [comment]
Same issue here, pulling my hair out.  I tried @ssh30 fix but it did not work for me.

**Reply by ssh30** [reply]
first you need to  create the ssh keys  on the server that  is going to run the docker compose using `ssh-keygen`  (don't use a passphrase) just Enter Enter Enter and do not change the location for the ssh files leave it as it is. 
After that  use  `ssh-copy-id user@server_ip_address`  against  every server that you need to control with Ansible.

Then within Semaphore  go to the Environment tab and inside the **Extra Variables** paste this 

`{ "ANSIBLE_HOST_KEY_CHECKING": "False" }`

On the Semaphore Keystore, create key of type **SSH key** and paste the content of the private key file **id_rsa**  not the **id_rsa.pub** that is inside the .ssh/ folder  

after that  mount the  volume the way i did , that  will pass the ssh public and private key folder into the container

**Reply by ssh30** [reply]
that's my compose file 

```
services:
  mysql:
    restart: unless-stopped
    image: mysql:8.0
    hostname: mysql
    volumes:
      - semaphore-mysql:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: semaphore
      MYSQL_USER: semaphore
      MYSQL_PASSWORD: xxxx
  semaphore:
    restart: unless-stopped
    ports:
      - 3000:3000
    image: semaphoreui/semaphore:latest
    volumes:
      - /home/devops/.ssh/:/home/semaphore/.ssh:ro  # Add this line, replace ./path/to/local/.ssh with the actual path to your .ssh directory
    environment:
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: semaphore
      SEMAPHORE_DB_HOST: mysql
      SEMAPHORE_DB_PORT: 3306
      SEMAPHORE_DB_DIALECT: mysql
      SEMAPHORE_DB: semaphore
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: xxxxxx
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      SEMAPHORE_LDAP_ACTIVATED: 'no'
    depends_on:
      - mysql
volumes:
  semaphore-mysql:
    driver: local
```

**Reply by Kupro404** [reply]
For me it would not work when the variable  **"ANSIBLE_HOST_KEY_CHECKING": "False"** was given through the ui I needed to put it in my docker compose file to work. Moreover another issue is that if the user is not specified within the key store when you create it, it will try to connect as **semaphore @192.168.x.x** and not **root @192.168.x.x** or any other user that you want to as expected. It says optional but it doesnt seem to work any other way except the ones i will mention bellow. So try putting root in the username field works for me.

Another way is to also include var   **ANSIBLE_REMOTE_USER: "root"**   in the compose file. This does the same job with above so you can skip the username part.

Lastly you can skip having to paste your keys in ui by either manually creating the ssh folder in **/home/semaphore/.ssh/id_rsa**  or by creating a volume of your ssh keys to the same path through the compose file. Then in your inventory specify the the path for the keys:
```
[target]
x.x.x.x   ansible_ssh_private_key_file=/home/semaphore/.ssh/id_rsa
```
With this you do not have to create an ssh option for the inventory and you can use a none one. 

The bellow compose file should work out of the box and you will only need to paste your private key in the key store or through the volumes method mentioned above.
```
services:
     # uncomment this section and comment out the mysql section to use postgres instead of mysql
     #postgres:
       #restart: unless-stopped
       #image: postgres:14
       #hostname: postgres
       #volumes:
       #  - semaphore-postgres:/var/lib/postgresql/data
       #environment:
      #  POSTGRES_USER: semaphore
      #  POSTGRES_PASSWORD: semaphore
      #  POSTGRES_DB: semaphore
    # if you wish to use postgres, comment the mysql service section below
  mysql:
    restart: unless-stopped
    image: mysql:8.0
    hostname: mysql
    volumes:
      - semaphore-mysql:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: semaphore
      MYSQL_USER: semaphore
      MYSQL_PASSWORD: semaphore
  semaphore:
    restart: unless-stopped
    ports:
      - 3000:3000
    image: semaphoreui/semaphore:latest
    environment:
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: semaphore
      SEMAPHORE_DB_HOST: mysql # for postgres, change to: postgres
      SEMAPHORE_DB_PORT: 3306 # change to 5432 for postgres
      SEMAPHORE_DB_DIALECT: mysql # for postgres, change to: postgres
      SEMAPHORE_DB: semaphore
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: changeme
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: c3bHOwIvsBZCHoaKY1ubWj3VFyxXSJnLc72iIwO/Pl0=
      ANSIBLE_REMOTE_USER: "root"
      ANSIBLE_HOST_KEY_CHECKING: "false"
        #SEMAPHORE_LDAP_ACTIVATED: 'no' # if you wish to use ldap, set to: 'yes'
        #SEMAPHORE_LDAP_HOST: dc01.local.example.com
        #SEMAPHORE_LDAP_PORT: '636'
        #SEMAPHORE_LDAP_NEEDTLS: 'yes'
        #SEMAPHORE_LDAP_DN_BIND: 'uid=bind_user,cn=users,cn=accounts,dc=local,dc=shiftsystems,dc=net'
        #SEMAPHORE_LDAP_PASSWORD: 'ldap_bind_account_password'
        #SEMAPHORE_LDAP_DN_SEARCH: 'dc=local,dc=example,dc=com'        
    depends_on:
      - mysql # for postgres, change to: postgres
volumes:
  semaphore-mysql

**Reply by fiftin** [reply]
I just installed Semaphore v2.9.64 from Docker Hub.

I added SSH key with Passphrase. And successfully connected to the server. I need details of your issue.

**Comment by Kupro404** [comment]
Mine too. What is the issue with it.

**Reply by fiftin** [reply]
I just installed Semaphore v2.9.64 from Docker Hub.

I added SSH key with Passphrase. And successfully connected to the server. I need details of your issue because I absolutelly don't understand what the problem.

**Reply by geelenbert** [reply]
I'm unable to use the SSH keys. 

Even for github it give this error:
```
9:49:28 AM
Task 1 added to queue
9:49:29 AM
Started: 1
9:49:29 AM
Run TaskRunner with template: update apt
9:49:29 AM
Preparing: 1
9:49:29 AM
Cloning Repository git@github.com:geelenbert/ansible.git
9:49:29 AM
Failed updating repository: parsing private key: ssh: no key found
9:49:29 AM
Running playbook failed: parsing private key: ssh: no key found
```

docker-compose.yaml:
```
services:
     # uncomment this section and comment out the mysql section to use postgres instead of mysql
     #postgres:
       #restart: unless-stopped
       #image: postgres:14
       #hostname: postgres
       #volumes:
       #  - semaphore-postgres:/var/lib/postgresql/data
       #environment:
      #  POSTGRES_USER: semaphore
      #  POSTGRES_PASSWORD: semaphore
      #  POSTGRES_DB: semaphore
    # if you wish to use postgres, comment the mysql service section below
  mysql:
    restart: unless-stopped
    image: mysql:8.0
    hostname: mysql
    volumes:
      - ./mysql/semaphore-mysql:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: semaphore
      MYSQL_USER: semaphore
      MYSQL_PASSWORD: semaphore
  semaphore:
    restart: unless-stopped
    ports:
      - 3000:3000
    image: semaphoreui/semaphore:latest
    environment:
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: semaphore
      SEMAPHORE_DB_HOST: mysql # for postgres, change to: postgres
      SEMAPHORE_DB_PORT: 3306 # change to 5432 for postgres
      SEMAPHORE_DB_DIALECT: mysql # for postgres, change to: postgres
      SEMAPHORE_DB: semaphore
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: adminpassword
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: c3bHOwIvsBZCHoaKY1ubWj3VFyxXSJnLc72iIwO/Pl0=
      # ANSIBLE_REMOTE_USER: "root"
      ANSIBLE_HOST_KEY_CHECKING: "false"
        #SEMAPHORE_LDAP_ACTIVATED: 'no' # if you wish to use ldap, set to: 'yes'
        #SEMAPHORE_LDAP_HOST: dc01.local.example.com
        #SEMAPHORE_LDAP_PORT: '636'
        #SEMAPHORE_LDAP_NEEDTLS: 'yes'
        #SEMAPHORE_LDAP_DN_BIND: 'uid=bind_user,cn=users,cn=accounts,dc=local,dc=shiftsystems,dc=net'
        #SEMAPHORE_LDAP_PASSWORD: 'ldap_bind_account_password'
        #SEMAPHORE_LDAP_DN_SEARCH: 'dc=local,dc=example,dc=com'
    depends_on:
      - mysql # for postgres, change to: postgres
volumes:
  semaphore-mysql:
    driver: local
    
```
<img width="445" alt="Screenshot 2024-04-06 at 09 55 46" src="https://github.com/semaphoreui/semaphore/assets/91923/66f3323e-19a1-410f-adba-e77ae1604d6a">
<img width="695" alt="Screenshot 2024-04-06 at 09 55 30" src="https://github.com/semaphoreui/semaphore/assets/91923/5aced48a-5517-4ce6-8833-b2c75484036e">
<img width="392" alt="Screenshot 2024-04-06 at 09 54 33" src="https://github.com/semaphoreui/semaphore/assets/91923/09fc8bce-1d3b-4dd4-9ae1-817c9dd7eb4d">
<img width="1168" alt="Screenshot 2024-04-06 at 09 55 02" src="https://github.com/semaphoreui/semaphore/assets/91923/199fccc9-ebcb-411e-8a80-3d0050dc3811">

SSH keys have a passphrase and authentication is working for other SSH sessions.

Semaphore v2.9.64
